#!/bin/bash
echo "ALX"
^C
root@5447bd9b4cc2:/alx-pre_course/0x01-git/bash# clear
root@5447bd9b4cc2:/alx-pre_course/0x01-git/bash# cat > school
#!/bin/bash
echo "School"
^C
root@5447bd9b4cc2:/alx-pre_course/0x01-git/bash# git add .
root@5447bd9b4cc2:/alx-pre_course/0x01-git/bash# git commit -m “Starting to code today, so cool”
root@5447bd9b4cc2:/alx-pre_course/0x01-git/bash# git push
root@5447bd9b4cc2:/alx-pre_course/0x01-git/bash# clear
root@5447bd9b4cc2:/alx-pre_course/0x01-git# clear
root@5447bd9b4cc2:/alx-pre_course/0x01-git#  clear
#!/bin/bash
echo "ALX" 
